export const LEGAL_EFFECTIVE_DATE = "April 5, 2026";
export const LEGAL_LAST_UPDATED = "April 5, 2026";

export const LEGAL_OPERATOR_NAME = "[INSERT LEGAL ENTITY NAME]";
export const LEGAL_CONTACT_EMAIL = "[INSERT LEGAL CONTACT EMAIL]";
export const LEGAL_MAILING_ADDRESS = "[INSERT LEGAL MAILING ADDRESS]";
export const LEGAL_PRIVACY_CONTACT = "[INSERT PRIVACY CONTACT NAME OR TITLE]";
export const LEGAL_PRIVACY_REQUEST_CHANNEL = "[INSERT PRIVACY REQUEST EMAIL OR SUPPORT CHANNEL]";
export const LEGAL_GOVERNING_JURISDICTION = "[INSERT PROVINCE OR TERRITORY]";
export const LEGAL_REFUND_NOTICE = "[INSERT FINAL CANCELLATION AND REFUND TERMS BEFORE LAUNCH]";
