import { test, expect, admin, createLocalSession, completeProfile, seedPortfolio, httpFixtures } from "./fixtures";

test("E2E-07: holding thesis snapshots persist and remain private", async ({ page, context, users, proof }) => {
  httpFixtures("E2E-07");
  await completeProfile(users.a);
  const portfolioId = await seedPortfolio(users.a);
  await createLocalSession(context, users.a);
  await page.goto(`/portfolio/full?portfolioId=${portfolioId}`);
  await page.getByRole("button", { name: /AAA/ }).first().click();
  const panel = page.getByRole("region", { name: "AAA investment thesis" });
  await panel.getByLabel("Thesis", { exact: true }).fill("Fixture thesis initial");
  await panel.getByLabel("Risks", { exact: true }).fill("Fixture first risk");
  await panel.getByRole("button", { name: "Save thesis" }).click();
  await expect.poll(async () => (await users.a.client.from("user_investment_thesis_history").select("thesis")).data).toEqual([{ thesis: "Fixture thesis initial" }]);
  await panel.getByLabel("Thesis", { exact: true }).fill("Fixture thesis revised");
  await panel.getByLabel("Risks", { exact: true }).fill("Fixture first risk\nFixture second risk");
  await panel.getByLabel("Horizon", { exact: true }).selectOption("long");
  await panel.getByLabel("Conviction", { exact: true }).selectOption("high");
  await panel.getByRole("button", { name: "Save thesis" }).click();
  await expect.poll(async () => (await users.a.client.from("user_investment_thesis_history").select("thesis").order("captured_at")).data).toEqual([{ thesis: "Fixture thesis initial" }, { thesis: "Fixture thesis revised" }]);
  await page.reload();
  await page.getByRole("button", { name: /AAA/ }).first().click();
  await expect(panel.getByLabel("Thesis", { exact: true })).toHaveValue("Fixture thesis revised");
  const saved = await users.a.client.from("user_investment_theses").select("id,scope,portfolio_id,risks,horizon,conviction").single();
  expect(saved.data).toMatchObject({ scope: "holding", portfolio_id: portfolioId, risks: ["Fixture first risk", "Fixture second risk"], horizon: "long", conviction: "high" });
  expect((await users.b.client.from("user_investment_theses").select("id")).data).toEqual([]);
  await users.b.client.from("user_investment_theses").update({ thesis: "Not allowed" }).eq("id", saved.data!.id);
  expect((await admin.from("user_investment_theses").select("thesis").eq("id", saved.data!.id).single()).data?.thesis).toBe("Fixture thesis revised");
  proof("create/update snapshots and holding-scope RLS; delete history deliberately unqualified", true);
});

test("E2E-08: real post/comment actions, Turnstile refusal and back navigation", async ({ page, context, users, proof }) => {
  const verify = { origin: "https://challenges.cloudflare.com", method: "POST", path: "/turnstile/v0/siteverify", body: { success: true, hostname: "127.0.0.1", action: "community", challenge_ts: new Date().toISOString() } };
  httpFixtures("E2E-08", [verify]);
  await completeProfile(users.a);
  await completeProfile(users.b);
  await createLocalSession(context, users.a);
  await page.goto("/community");
  await page.getByPlaceholder(/What's on your mind/).fill("Fixture original community post");
  await page.getByRole("button", { name: "Post", exact: true }).click();
  await expect(page.getByText("Fixture original community post", { exact: true })).toBeVisible();
  const post = await users.a.client.from("community_posts").select("id,body").eq("user_id", users.a.id).single();
  expect(post.data?.body).toBe("Fixture original community post");
  await createLocalSession(context, users.b);
  await page.reload();
  await page.getByRole("button", { name: /comment/i }).first().click();
  await expect(page.getByText("Fixture original community post", { exact: true }).last()).toBeVisible();
  await page.getByPlaceholder("Write a comment…").fill("Fixture comment from B");
  await page.getByPlaceholder("Write a comment…").press("Enter");
  await expect(page.getByText("Fixture comment from B", { exact: true })).toBeVisible();
  expect((await users.b.client.from("community_comments").select("body,user_id").eq("post_id", post.data!.id)).data).toEqual([{ body: "Fixture comment from B", user_id: users.b.id }]);
  await page.getByRole("button", { name: "Back to community" }).click();
  httpFixtures("E2E-08-refused", [{ ...verify, body: { success: false, "error-codes": ["invalid-input-response"] } }]);
  await page.getByPlaceholder(/What's on your mind/).fill("This post must never persist");
  await page.getByRole("button", { name: "Post", exact: true }).click();
  await expect(page.getByText(/Bot verification failed/)).toBeVisible();
  expect((await admin.from("community_posts").select("id").eq("body", "This post must never persist")).data).toEqual([]);
  proof("post/comment durable with real user sessions, widget transport, siteverify refusal and return UI", true);
});
